[window]
opacity = 0.88
blur = true
dynamic_padding = true
padding = { x = 2, y = 2 }

[font]
size = 13.3
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
bold = { family = "SauceCodePro Nerd Font Mono", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font Mono", style = "Bold Italic" }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#dbdbdb"
background = "#0E151C"
# background = "#14191e"

[colors.normal]
black = "#14191e"
red = "#b43c29"
green = "#00c200"
yellow = "#c7c400"
blue = "#2743c7"
magenta = "#bf3fbd"
cyan = "#00c5c7"
white = "#c7c7c7"

[colors.bright]
black = "#676767"
red = "#dc7974"
green = "#57e690"
yellow = "#ece100"
blue = "#a6aaf1"
magenta = "#e07de0"
cyan = "#5ffdff"
white = "#feffff"

